[package]
name = "yaak_templates"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ts-rs = { workspace = true}
tokio = { version = "1.39.3", features = ["macros", "rt"] }
