// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerSentEvent = { eventType: string, data: string, id: string | null, retry: bigint | null, };
