// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CookieDomain = { "HostOnly": string } | { "Suffix": string } | "NotPresent" | "Empty";
