// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncChangeItem } from "./sync";

export type ChangesPayload = { workspaceId: string, branch: string, };

export type CommitPayload = { workspaceId: string, message: string, branch: string, changeItems: Array<SyncChangeItem>, };
