// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangesPayload = { workspaceId: string, branch: string, };

export type CommitPayload = { workspaceId: string, message: string, branch: string, addedIds: Array<string>, };

export type CommitsPayload = { workspaceId: string, branch: string, };
