// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncModel } from './models';
import type { SyncObject } from './models';

export type StageStatus = 'unmodified' | 'modified' | 'untracked' | 'removed';

export type StageTreeNode = {
  model: SyncModel;
  children: Array<StageTreeNode>;
  status: StageStatus;
  objectId: string;
  prevObject: SyncObject | null;
  nextObject: SyncObject | null;
  depth: number;
};
