// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncModel } from "./models";

export type SyncChange = { prev: SyncChangeItem | null, next: SyncChangeItem | null, };

export type SyncChangeItem = { hash: string, model: SyncModel, };
