name: Bug Report
description: "Something isn't working properly in Yaak"
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees:
  - gschier
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report 🤗
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: 2024.8.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you on?
      multiple: false
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
