// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FnArg = { name: string, value: Val, };

export type Token = { "type": "raw", text: string, } | { "type": "tag", val: Val, } | { "type": "eof" };

export type Tokens = { tokens: Array<Token>, };

export type Val = { "type": "str", text: string, } | { "type": "var", name: string, } | { "type": "bool", value: boolean, } | { "type": "fn", name: string, args: Array<FnArg>, } | { "type": "null" };
