// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncModel } from "./models";

export type SyncDiff = { "type": "unmodified", model: SyncModel, } | { "type": "removed", model: SyncModel, } | { "type": "modified", prev: SyncModel, model: SyncModel, } | { "type": "added", model: SyncModel, };
