// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncObject = { metadata: SyncObjectMetadata, data: string, };

export type SyncObjectMetadata = { hash: string, id: string, model: string, created_at: string, updated_at: string, name: string | null, folder_id: string | null, workspace_id: string | null, };
