// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Environment } from "./models";
import type { Folder } from "./models";
import type { GrpcRequest } from "./models";
import type { HttpRequest } from "./models";
import type { Workspace } from "./models";

export type SyncModel = Workspace | Environment | Folder | HttpRequest | GrpcRequest;
