// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Protocol = 2,
  Host = 3,
  Port = 4,
  Path = 5,
  Placeholder = 6,
  PathSegment = 7,
  Query = 8
