// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  url = 1,
  Protocol = 2,
  Host = 3,
  Port = 4,
  Path = 5,
  Slash = 6,
  PathSegment = 7,
  Query = 8,
  Question = 9,
  QueryPair = 10,
  Amp = 11,
  QueryName = 12,
  Equal = 13,
  QueryValue = 14
