// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  url = 1,
  Protocol = 2,
  ProtocolName = 3,
  Slashy = 4,
  Host = 5,
  Path = 6,
  Slash = 7,
  PathSegment = 8,
  Query = 9,
  Question = 10,
  QueryPair = 11,
  Amp = 12,
  QueryName = 13,
  Equal = 14,
  QueryValue = 15
