// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
import {highlight} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QOQOPOOOOOO'#C_'#C_OYOQO'#C^QOOOOOOOOO'#Cc'#CcO_OQO,58xOOOO-E6a-E6aOOOO1G.d1G.d",
  stateData: "g~OUROXPO~OSSO~OSSOTVO~O",
  goto: "eWPPX[PPP_RRORQOQTQRUT",
  nodeNames: "⚠ Template Tag Open Content Close Text",
  maxTerm: 9,
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!S~RTOtbtugu;'Sb;'S;=`z;=`Ob~gOU~~lPU~#o#po~rP!}#Ou~zOX~~!PPU~;=`<%lb",
  tokenizers: [1, new LocalTokenGroup("b~RP#P#QU~XP#q#r[~aOT~~", 17, 4)],
  topRules: {"Template":[0,1]},
  tokenPrec: 0
})
